// Maps FM24 HTML export abbreviated headers to full Spanish attribute names.
// The full names match exactly what FM26 CSV exports use, so roles can share attribute definitions.
export const FM24_ATTR_MAP: Record<string, string> = {
  "Dec":  "Decisiones",
  "Det":  "Determinación",
  "JEq":  "Trabajo de equipo",
  "Lid":  "Liderazgo",
  "Mar":  "Marcaje",
  "Ser":  "Serenidad",
  "Aér":  "Alcance aéreo",
  "Com":  "Comunicación",
  "Exc":  "Excentricidad",
  "Pas":  "Pases",
  "Blo":  "Blocaje",
  "Puñ":  "Puños",
  "Sq L": "Saques largos",
  "Mdo":  "Mando en el área",
  "Val":  "Valentía",
  "Pue":  "Paradas",
  "Pen":  "Penaltis",
  "Téc":  "Técnica",
  "Lej":  "Tiros lejanos",
  "1v1":  "Uno contra uno",
  "Saq":  "Saques de puerta",
  "Lib":  "Saques de banda",
  "Ref":  "Reflejos",
  "Cab":  "Cabeceo",
  "Reg":  "Regate",
  "Cen":  "Centros",
  "Rem":  "Remate",
  "Vis":  "Visión",
  "Ctr":  "Control",
  "SAL":  "Salidas",
  "Cór":  "Córneres",
  "Tal":  "Talento",
  "Ent":  "Entradas",
  "Sac":  "Sacrificio",
  "Ace":  "Aceleración",
  "Agi":  "Agilidad",
  "Equ":  "Equilibrio",
  "Sal":  "Alcance de salto",
  "Fís":  "Recuperación física",
  "Vel":  "Velocidad",
  "Res":  "Resistencia",
  "Fue":  "Fuerza",
  "Dmq":  "Desmarques",
  "Cnc":  "Concentración",
  "Col":  "Colocación",
  "Ant":  "Anticipación",
  "Agr":  "Agresividad",
};

export function mapFm24Header(abbr: string): string {
  return FM24_ATTR_MAP[abbr] ?? abbr;
}
