import { Role } from "./types";

const POS_POR     = ["POR"];
const POS_LAT     = ["DF-D", "DF-I", "CR-D", "CR-I"];
const POS_DC      = ["DF-C"];
const POS_MC      = ["MC"];
const POS_ME      = ["ME-D", "ME-I", "ME-C"];
const POS_MP_EXT  = ["MP-D", "MP-I"];
const POS_MP_C    = ["MP-C"];
const POS_DL      = ["DL-C"];

export const ALL_ROLES_FM24: Role[] = [
  // PORTERO
  {
    id: "portero",
    name: "Portero",
    group: "Portero",
    positionKeys: POS_POR,
    keyAttributes: ["Blocaje", "Alcance aéreo", "Mando en el área", "Comunicación", "Colocación", "Reflejos", "Agilidad", "Concentración"],
    preferredAttributes: ["Saques de puerta", "Velocidad", "Decisiones", "Trabajo de equipo"],
  },
  {
    id: "portero-cierre",
    name: "Portero cierre",
    group: "Portero",
    positionKeys: POS_POR,
    keyAttributes: ["Blocaje", "Alcance aéreo", "Mando en el área", "Comunicación", "Colocación", "Reflejos", "Agilidad", "Concentración"],
    preferredAttributes: ["Saques de puerta", "Velocidad", "Decisiones", "Trabajo de equipo"],
  },

  // LATERAL / CARRILERO
  {
    id: "lateral",
    name: "Lateral",
    group: "Lateral / Carrilero",
    positionKeys: POS_LAT,
    keyAttributes: ["Marcaje", "Entradas", "Anticipación", "Colocación", "Trabajo de equipo", "Aceleración", "Concentración"],
    preferredAttributes: ["Cabeceo", "Pases", "Decisiones", "Velocidad"],
  },
  {
    id: "carrilero",
    name: "Carrilero",
    group: "Lateral / Carrilero",
    positionKeys: POS_LAT,
    keyAttributes: ["Centros", "Marcaje", "Entradas", "Trabajo de equipo", "Sacrificio", "Aceleración", "Resistencia", "Velocidad"],
    preferredAttributes: ["Técnica", "Desmarques", "Colocación"],
  },
  {
    id: "lateral-practico",
    name: "Lateral práctico",
    group: "Lateral / Carrilero",
    positionKeys: POS_LAT,
    keyAttributes: ["Marcaje", "Entradas", "Anticipación", "Colocación", "Trabajo de equipo", "Concentración"],
    preferredAttributes: ["Cabeceo", "Fuerza", "Decisiones", "Resistencia"],
  },
  {
    id: "carrilero-completo",
    name: "Carrilero completo",
    group: "Lateral / Carrilero",
    positionKeys: POS_LAT,
    keyAttributes: ["Centros", "Regate", "Desmarques", "Técnica", "Trabajo de equipo", "Sacrificio", "Aceleración", "Resistencia"],
    preferredAttributes: ["Velocidad", "Agilidad", "Decisiones"],
  },
  {
    id: "carrilero-inverso",
    name: "Carrilero inverso",
    group: "Lateral / Carrilero",
    positionKeys: POS_LAT,
    keyAttributes: ["Pases", "Entradas", "Anticipación", "Decisiones", "Colocación", "Trabajo de equipo", "Aceleración", "Serenidad"],
    preferredAttributes: ["Técnica", "Visión", "Concentración"],
  },
  {
    id: "lateral-inverso",
    name: "Lateral inverso",
    group: "Lateral / Carrilero",
    positionKeys: POS_LAT,
    keyAttributes: ["Cabeceo", "Marcaje", "Entradas", "Anticipación", "Colocación", "Fuerza"],
    preferredAttributes: ["Trabajo de equipo", "Concentración", "Alcance de salto"],
  },

  // DEFENSA CENTRAL
  {
    id: "defensa-central",
    name: "Defensa central",
    group: "Defensa Central",
    positionKeys: POS_DC,
    keyAttributes: ["Cabeceo", "Marcaje", "Entradas", "Anticipación", "Colocación", "Fuerza", "Alcance de salto"],
    preferredAttributes: ["Agresividad", "Trabajo de equipo", "Concentración"],
  },
  {
    id: "libero",
    name: "Líbero",
    group: "Defensa Central",
    positionKeys: POS_DC,
    keyAttributes: ["Cabeceo", "Marcaje", "Pases", "Entradas", "Anticipación", "Decisiones", "Colocación", "Técnica"],
    preferredAttributes: ["Visión", "Fuerza", "Alcance de salto"],
  },
  {
    id: "defensa-con-toque",
    name: "Defensa con toque",
    group: "Defensa Central",
    positionKeys: POS_DC,
    keyAttributes: ["Cabeceo", "Marcaje", "Pases", "Entradas", "Anticipación", "Colocación", "Fuerza", "Alcance de salto"],
    preferredAttributes: ["Técnica", "Visión", "Decisiones"],
  },
  {
    id: "central-practico",
    name: "Central práctico",
    group: "Defensa Central",
    positionKeys: POS_DC,
    keyAttributes: ["Cabeceo", "Marcaje", "Entradas", "Anticipación", "Colocación", "Fuerza", "Alcance de salto"],
    preferredAttributes: ["Agresividad", "Trabajo de equipo", "Concentración"],
  },
  {
    id: "central-lateral",
    name: "Central lateral",
    group: "Defensa Central",
    positionKeys: POS_DC,
    keyAttributes: ["Cabeceo", "Marcaje", "Pases", "Entradas", "Anticipación", "Decisiones", "Colocación", "Técnica"],
    preferredAttributes: ["Visión", "Serenidad", "Fuerza"],
  },

  // MEDIOCENTRO
  {
    id: "mediocentro",
    name: "Mediocentro",
    group: "Mediocentro",
    positionKeys: POS_MC,
    keyAttributes: ["Entradas", "Anticipación", "Colocación", "Trabajo de equipo", "Concentración"],
    preferredAttributes: ["Pases", "Decisiones", "Resistencia"],
  },
  {
    id: "pivote-organizador",
    name: "Pivote organizador",
    group: "Mediocentro",
    positionKeys: POS_MC,
    keyAttributes: ["Pases", "Visión", "Decisiones", "Control", "Técnica", "Trabajo de equipo", "Serenidad"],
    preferredAttributes: ["Entradas", "Colocación", "Anticipación"],
  },
  {
    id: "centrocampista-recuperador-mc",
    name: "Centrocampista recuperador",
    group: "Mediocentro",
    positionKeys: POS_MC,
    keyAttributes: ["Entradas", "Marcaje", "Anticipación", "Agresividad", "Concentración", "Trabajo de equipo"],
    preferredAttributes: ["Fuerza", "Colocación", "Decisiones"],
  },
  {
    id: "pivote-defensivo",
    name: "Pivote defensivo",
    group: "Mediocentro",
    positionKeys: POS_MC,
    keyAttributes: ["Entradas", "Marcaje", "Anticipación", "Colocación", "Concentración", "Trabajo de equipo"],
    preferredAttributes: ["Fuerza", "Pases", "Decisiones"],
  },
  {
    id: "medio-cierre",
    name: "Medio cierre",
    group: "Mediocentro",
    positionKeys: POS_MC,
    keyAttributes: ["Cabeceo", "Marcaje", "Entradas", "Anticipación", "Colocación", "Trabajo de equipo", "Fuerza", "Alcance de salto"],
    preferredAttributes: ["Concentración", "Decisiones"],
  },
  {
    id: "regista",
    name: "Regista",
    group: "Mediocentro",
    positionKeys: POS_MC,
    keyAttributes: ["Entradas", "Marcaje", "Anticipación", "Agresividad", "Concentración", "Fuerza"],
    preferredAttributes: ["Trabajo de equipo", "Colocación", "Decisiones"],
  },
  {
    id: "organizador-itinerante-mc",
    name: "Organizador itinerante",
    group: "Mediocentro",
    positionKeys: POS_MC,
    keyAttributes: ["Desmarques", "Pases", "Visión", "Decisiones", "Control", "Técnica", "Trabajo de equipo", "Sacrificio"],
    preferredAttributes: ["Resistencia", "Serenidad", "Anticipación"],
  },
  {
    id: "segundo-volante",
    name: "Segundo volante",
    group: "Mediocentro",
    positionKeys: POS_MC,
    keyAttributes: ["Entradas", "Desmarques", "Pases", "Decisiones", "Trabajo de equipo", "Sacrificio"],
    preferredAttributes: ["Técnica", "Resistencia", "Anticipación"],
  },

  // CENTROCAMPISTA
  {
    id: "centrocampista",
    name: "Centrocampista",
    group: "Centrocampista",
    positionKeys: POS_ME,
    keyAttributes: ["Pases", "Entradas", "Decisiones", "Control", "Trabajo de equipo"],
    preferredAttributes: ["Técnica", "Desmarques", "Colocación"],
  },
  {
    id: "pivote-organizador-me",
    name: "Pivote organizador",
    group: "Centrocampista",
    positionKeys: POS_ME,
    keyAttributes: ["Pases", "Visión", "Decisiones", "Control", "Técnica", "Trabajo de equipo", "Serenidad"],
    preferredAttributes: ["Entradas", "Colocación", "Anticipación"],
  },
  {
    id: "centrocampista-todoterreno",
    name: "Centrocampista todoterreno",
    group: "Centrocampista",
    positionKeys: POS_ME,
    keyAttributes: ["Desmarques", "Pases", "Entradas", "Trabajo de equipo", "Sacrificio", "Resistencia"],
    preferredAttributes: ["Decisiones", "Colocación", "Anticipación"],
  },
  {
    id: "organizador-adelantado-me",
    name: "Organizador adelantado",
    group: "Centrocampista",
    positionKeys: POS_ME,
    keyAttributes: ["Desmarques", "Pases", "Visión", "Decisiones", "Control", "Técnica", "Trabajo de equipo", "Serenidad"],
    preferredAttributes: ["Regate", "Talento", "Anticipación"],
  },
  {
    id: "centrocampista-recuperador-me",
    name: "Centrocampista recuperador",
    group: "Centrocampista",
    positionKeys: POS_ME,
    keyAttributes: ["Entradas", "Marcaje", "Anticipación", "Agresividad", "Concentración", "Trabajo de equipo"],
    preferredAttributes: ["Fuerza", "Colocación", "Decisiones"],
  },
  {
    id: "organizador-itinerante-me",
    name: "Organizador itinerante",
    group: "Centrocampista",
    positionKeys: POS_ME,
    keyAttributes: ["Desmarques", "Pases", "Visión", "Decisiones", "Control", "Técnica", "Trabajo de equipo", "Sacrificio"],
    preferredAttributes: ["Resistencia", "Serenidad", "Anticipación"],
  },
  {
    id: "mezzala",
    name: "Mezzala",
    group: "Centrocampista",
    positionKeys: POS_ME,
    keyAttributes: ["Regate", "Desmarques", "Pases", "Técnica", "Aceleración", "Serenidad"],
    preferredAttributes: ["Visión", "Decisiones", "Tiros lejanos"],
  },
  {
    id: "interior-mixto",
    name: "Interior Mixto",
    group: "Centrocampista",
    positionKeys: POS_ME,
    keyAttributes: ["Centros", "Desmarques", "Pases", "Control", "Técnica", "Sacrificio", "Aceleración", "Serenidad"],
    preferredAttributes: ["Regate", "Decisiones", "Trabajo de equipo"],
  },

  // EXTERIOR (ME banda)
  {
    id: "centrocampista-de-banda",
    name: "Centrocampista de banda",
    group: "Exterior",
    positionKeys: POS_ME,
    keyAttributes: ["Centros", "Pases", "Decisiones", "Técnica", "Trabajo de equipo", "Sacrificio", "Resistencia", "Velocidad"],
    preferredAttributes: ["Regate", "Desmarques", "Control"],
  },
  {
    id: "extremo-me",
    name: "Extremo",
    group: "Exterior",
    positionKeys: POS_ME,
    keyAttributes: ["Centros", "Regate", "Técnica", "Trabajo de equipo", "Aceleración", "Velocidad", "Agilidad"],
    preferredAttributes: ["Desmarques", "Control", "Decisiones"],
  },
  {
    id: "extremo-defensivo",
    name: "Extremo defensivo",
    group: "Exterior",
    positionKeys: POS_ME,
    keyAttributes: ["Centros", "Marcaje", "Entradas", "Trabajo de equipo", "Aceleración", "Velocidad", "Resistencia"],
    preferredAttributes: ["Regate", "Decisiones", "Colocación"],
  },
  {
    id: "organizador-en-banda",
    name: "Organizador en banda",
    group: "Exterior",
    positionKeys: POS_ME,
    keyAttributes: ["Centros", "Regate", "Desmarques", "Pases", "Visión", "Decisiones", "Control", "Técnica"],
    preferredAttributes: ["Trabajo de equipo", "Serenidad", "Aceleración"],
  },
  {
    id: "extremo-inverso-me",
    name: "Extremo inverso",
    group: "Exterior",
    positionKeys: POS_ME,
    keyAttributes: ["Regate", "Control", "Técnica", "Trabajo de equipo", "Aceleración", "Agilidad", "Serenidad"],
    preferredAttributes: ["Desmarques", "Pases", "Decisiones"],
  },

  // MEDIAPUNTA EXTERIOR (MP D/I)
  {
    id: "extremo-mp",
    name: "Extremo",
    group: "Mediapunta Exterior",
    positionKeys: POS_MP_EXT,
    keyAttributes: ["Centros", "Regate", "Técnica", "Trabajo de equipo", "Aceleración", "Velocidad", "Agilidad"],
    preferredAttributes: ["Desmarques", "Control", "Decisiones"],
  },
  {
    id: "organizador-adelantado-mp-ext",
    name: "Organizador adelantado",
    group: "Mediapunta Exterior",
    positionKeys: POS_MP_EXT,
    keyAttributes: ["Centros", "Regate", "Desmarques", "Pases", "Visión", "Decisiones", "Control", "Técnica"],
    preferredAttributes: ["Trabajo de equipo", "Serenidad", "Aceleración"],
  },
  {
    id: "trequartista-mp-ext",
    name: "Trequartista",
    group: "Mediapunta Exterior",
    positionKeys: POS_MP_EXT,
    keyAttributes: ["Regate", "Tiros lejanos", "Pases", "Visión", "Control", "Técnica", "Talento"],
    preferredAttributes: ["Decisiones", "Serenidad", "Desmarques"],
  },
  {
    id: "delantero-objetivo-escorado",
    name: "Delantero objetivo escorado",
    group: "Mediapunta Exterior",
    positionKeys: POS_MP_EXT,
    keyAttributes: ["Regate", "Desmarques", "Anticipación", "Control", "Técnica", "Aceleración", "Velocidad", "Agilidad"],
    preferredAttributes: ["Remate", "Trabajo de equipo", "Concentración"],
  },
  {
    id: "buscador-de-espacios",
    name: "Buscador de espacios",
    group: "Mediapunta Exterior",
    positionKeys: POS_MP_EXT,
    keyAttributes: ["Regate", "Desmarques", "Anticipación", "Control", "Aceleración", "Agilidad", "Serenidad"],
    preferredAttributes: ["Remate", "Velocidad", "Técnica"],
  },
  {
    id: "extremo-inverso-mp",
    name: "Extremo inverso",
    group: "Mediapunta Exterior",
    positionKeys: POS_MP_EXT,
    keyAttributes: ["Regate", "Control", "Técnica", "Trabajo de equipo", "Aceleración", "Agilidad", "Serenidad"],
    preferredAttributes: ["Desmarques", "Pases", "Decisiones"],
  },

  // MEDIAPUNTA CENTRAL (MP C)
  {
    id: "mediapunta",
    name: "Mediapunta",
    group: "Mediapunta",
    positionKeys: POS_MP_C,
    keyAttributes: ["Tiros lejanos", "Desmarques", "Pases", "Control", "Técnica", "Talento", "Serenidad"],
    preferredAttributes: ["Regate", "Visión", "Decisiones"],
  },
  {
    id: "organizador-adelantado-mp-c",
    name: "Organizador adelantado",
    group: "Mediapunta",
    positionKeys: POS_MP_C,
    keyAttributes: ["Desmarques", "Pases", "Visión", "Decisiones", "Control", "Técnica", "Trabajo de equipo", "Serenidad"],
    preferredAttributes: ["Regate", "Talento", "Anticipación"],
  },
  {
    id: "trequartista-mp-c",
    name: "Trequartista",
    group: "Mediapunta",
    positionKeys: POS_MP_C,
    keyAttributes: ["Regate", "Tiros lejanos", "Pases", "Visión", "Control", "Técnica", "Talento"],
    preferredAttributes: ["Decisiones", "Serenidad", "Desmarques"],
  },
  {
    id: "enganche",
    name: "Enganche",
    group: "Mediapunta",
    positionKeys: POS_MP_C,
    keyAttributes: ["Pases", "Visión", "Decisiones", "Control", "Técnica", "Talento", "Serenidad"],
    preferredAttributes: ["Tiros lejanos", "Regate", "Desmarques"],
  },
  {
    id: "delantero-sorpresa",
    name: "Delantero sorpresa",
    group: "Mediapunta",
    positionKeys: POS_MP_C,
    keyAttributes: ["Remate", "Desmarques", "Anticipación", "Control", "Aceleración", "Serenidad"],
    preferredAttributes: ["Técnica", "Decisiones", "Trabajo de equipo"],
  },

  // DELANTERO CENTRO
  {
    id: "segundo-delantero",
    name: "Segundo delantero",
    group: "Delantero",
    positionKeys: POS_DL,
    keyAttributes: ["Remate", "Desmarques", "Anticipación", "Control", "Aceleración", "Serenidad"],
    preferredAttributes: ["Técnica", "Decisiones", "Trabajo de equipo"],
  },
  {
    id: "delantero-avanzado",
    name: "Delantero avanzado",
    group: "Delantero",
    positionKeys: POS_DL,
    keyAttributes: ["Remate", "Cabeceo", "Desmarques", "Control", "Técnica", "Aceleración", "Fuerza", "Serenidad"],
    preferredAttributes: ["Decisiones", "Anticipación", "Trabajo de equipo"],
  },
  {
    id: "delantero-objetivo",
    name: "Delantero objetivo",
    group: "Delantero",
    positionKeys: POS_DL,
    keyAttributes: ["Remate", "Cabeceo", "Desmarques", "Fuerza", "Alcance de salto", "Equilibrio", "Valentía", "Agresividad"],
    preferredAttributes: ["Anticipación", "Decisiones", "Trabajo de equipo"],
  },
  {
    id: "ariete",
    name: "Ariete",
    group: "Delantero",
    positionKeys: POS_DL,
    keyAttributes: ["Remate", "Cabeceo", "Desmarques", "Anticipación", "Aceleración", "Serenidad", "Concentración"],
    preferredAttributes: ["Decisiones", "Trabajo de equipo", "Velocidad"],
  },
  {
    id: "delantero-completo",
    name: "Delantero completo",
    group: "Delantero",
    positionKeys: POS_DL,
    keyAttributes: ["Remate", "Cabeceo", "Desmarques", "Regate", "Control", "Técnica", "Aceleración", "Serenidad"],
    preferredAttributes: ["Fuerza", "Decisiones", "Trabajo de equipo"],
  },
  {
    id: "delantero-presionante",
    name: "Delantero presionante",
    group: "Delantero",
    positionKeys: POS_DL,
    keyAttributes: ["Remate", "Desmarques", "Aceleración", "Sacrificio", "Resistencia", "Concentración"],
    preferredAttributes: ["Control", "Decisiones", "Trabajo de equipo"],
  },
  {
    id: "trequartista-dl",
    name: "Trequartista",
    group: "Delantero",
    positionKeys: POS_DL,
    keyAttributes: ["Regate", "Tiros lejanos", "Pases", "Visión", "Control", "Técnica", "Talento"],
    preferredAttributes: ["Decisiones", "Serenidad", "Desmarques"],
  },
  {
    id: "falso-nueve",
    name: "Falso nueve",
    group: "Delantero",
    positionKeys: POS_DL,
    keyAttributes: ["Regate", "Desmarques", "Pases", "Visión", "Decisiones", "Control", "Técnica", "Trabajo de equipo"],
    preferredAttributes: ["Resistencia", "Serenidad", "Anticipación"],
  },
];
