import { Role } from "./types";

// Position keys that map to each role group
const POS_POR = ["POR"];
const POS_LAT = ["DF-D", "DF-I", "CR-D", "CR-I"];
const POS_DC = ["DF-C"];
const POS_MC = ["MC"];
const POS_ME = ["ME-D", "ME-I", "ME-C"];
const POS_MP_EXT = ["MP-D", "MP-I"];
const POS_MP_C = ["MP-C"];
const POS_DL = ["DL-C"];

export const ALL_ROLES: Role[] = [
  // PORTERO
  {
    id: "portero",
    name: "Portero",
    group: "Portero",
    positionKeys: POS_POR,
    keyAttributes: ["Blocaje", "Alcance aéreo", "Mando en el área", "Comunicación", "Colocación", "Reflejos", "Agilidad", "Concentración"],
    preferredAttributes: ["Saques de puerta", "Velocidad", "Decisiones", "Trabajo de equipo"],
  },
  {
    id: "portero-juego-pies",
    name: "Portero con juego de pies",
    group: "Portero",
    positionKeys: POS_POR,
    keyAttributes: ["Blocaje", "Alcance aéreo", "Mando en el área", "Comunicación", "Saques de puerta", "Colocación", "Reflejos", "Agilidad"],
    preferredAttributes: ["Velocidad", "Decisiones", "Trabajo de equipo", "Concentración"],
  },
  {
    id: "portero-sin-complicaciones",
    name: "Portero sin complicaciones",
    group: "Portero",
    positionKeys: POS_POR,
    keyAttributes: ["Blocaje", "Alcance aéreo", "Mando en el área", "Comunicación", "Colocación", "Reflejos", "Agilidad", "Concentración"],
    preferredAttributes: ["Saques de puerta", "Velocidad", "Decisiones", "Trabajo de equipo"],
  },

  // LATERAL Y/O CARRILERO
  {
    id: "lateral-defensivo",
    name: "Lateral defensivo",
    group: "Lateral / Carrilero",
    positionKeys: POS_LAT,
    keyAttributes: ["Marcaje", "Entradas", "Anticipación", "Colocación", "Trabajo de equipo", "Aceleración", "Concentración"],
    preferredAttributes: ["Cabeceo", "Pases", "Decisiones", "Velocidad"],
  },
  {
    id: "lateral-ofensivo",
    name: "Lateral ofensivo",
    group: "Lateral / Carrilero",
    positionKeys: POS_LAT,
    keyAttributes: ["Centros", "Marcaje", "Entradas", "Trabajo de equipo", "Sacrificio", "Aceleración", "Resistencia", "Velocidad"],
    preferredAttributes: ["Técnica", "Desmarques", "Colocación"],
  },
  {
    id: "carrilero-por-dentro",
    name: "Carrilero por dentro",
    group: "Lateral / Carrilero",
    positionKeys: POS_LAT,
    keyAttributes: ["Pases", "Entradas", "Anticipación", "Decisiones", "Colocación", "Trabajo de equipo", "Aceleración", "Serenidad"],
    preferredAttributes: ["Técnica", "Visión", "Concentración"],
  },
  {
    id: "lateral-por-dentro",
    name: "Lateral por dentro",
    group: "Lateral / Carrilero",
    positionKeys: POS_LAT,
    keyAttributes: ["Cabeceo", "Marcaje", "Entradas", "Anticipación", "Colocación", "Fuerza"],
    preferredAttributes: ["Trabajo de equipo", "Concentración", "Alcance de salto"],
  },
  {
    id: "lateral-ofensivo-creador",
    name: "Lateral ofensivo creador",
    group: "Lateral / Carrilero",
    positionKeys: POS_LAT,
    keyAttributes: ["Pases", "Entradas", "Visión", "Decisiones", "Control", "Técnica", "Trabajo de equipo", "Aceleración"],
    preferredAttributes: ["Centros", "Regate", "Serenidad"],
  },
  {
    id: "lateral-ofensivo-avanzado",
    name: "Lateral ofensivo avanzado",
    group: "Lateral / Carrilero",
    positionKeys: POS_LAT,
    keyAttributes: ["Centros", "Regate", "Desmarques", "Técnica", "Trabajo de equipo", "Sacrificio", "Aceleración", "Resistencia"],
    preferredAttributes: ["Velocidad", "Agilidad", "Decisiones"],
  },

  // DEFENSA CENTRAL
  {
    id: "central",
    name: "Central",
    group: "Defensa Central",
    positionKeys: POS_DC,
    keyAttributes: ["Cabeceo", "Marcaje", "Entradas", "Anticipación", "Colocación", "Fuerza", "Alcance de salto"],
    preferredAttributes: ["Agresividad", "Trabajo de equipo", "Concentración"],
  },
  {
    id: "central-avanzado",
    name: "Central avanzado",
    group: "Defensa Central",
    positionKeys: POS_DC,
    keyAttributes: ["Cabeceo", "Marcaje", "Pases", "Entradas", "Anticipación", "Decisiones", "Colocación", "Técnica"],
    preferredAttributes: ["Visión", "Serenidad", "Fuerza"],
  },
  {
    id: "central-con-toque",
    name: "Central con toque",
    group: "Defensa Central",
    positionKeys: POS_DC,
    keyAttributes: ["Cabeceo", "Marcaje", "Pases", "Entradas", "Anticipación", "Colocación", "Fuerza", "Alcance de salto"],
    preferredAttributes: ["Técnica", "Visión", "Decisiones"],
  },
  {
    id: "central-defensivo",
    name: "Central defensivo",
    group: "Defensa Central",
    positionKeys: POS_DC,
    keyAttributes: ["Cabeceo", "Marcaje", "Entradas", "Anticipación", "Colocación", "Fuerza", "Alcance de salto"],
    preferredAttributes: ["Agresividad", "Trabajo de equipo", "Concentración"],
  },

  // MEDIOCENTRO
  {
    id: "mediocentro",
    name: "Mediocentro",
    group: "Mediocentro",
    positionKeys: POS_MC,
    keyAttributes: ["Entradas", "Anticipación", "Colocación", "Trabajo de equipo", "Concentración"],
    preferredAttributes: ["Pases", "Decisiones", "Resistencia"],
  },
  {
    id: "pivote-organizador",
    name: "Pivote organizador",
    group: "Mediocentro",
    positionKeys: POS_MC,
    keyAttributes: ["Pases", "Visión", "Decisiones", "Control", "Técnica", "Trabajo de equipo", "Serenidad"],
    preferredAttributes: ["Entradas", "Colocación", "Anticipación"],
  },
  {
    id: "centrocampista-todoterreno",
    name: "Centrocampista todoterreno",
    group: "Mediocentro",
    positionKeys: POS_MC,
    keyAttributes: ["Desmarques", "Pases", "Entradas", "Trabajo de equipo", "Sacrificio", "Resistencia"],
    preferredAttributes: ["Decisiones", "Colocación", "Anticipación"],
  },
  {
    id: "medio-cierre",
    name: "Medio cierre",
    group: "Mediocentro",
    positionKeys: POS_MC,
    keyAttributes: ["Cabeceo", "Marcaje", "Entradas", "Anticipación", "Colocación", "Trabajo de equipo", "Fuerza", "Alcance de salto"],
    preferredAttributes: ["Concentración", "Decisiones"],
  },
  {
    id: "organizador-todoterreno",
    name: "Organizador todoterreno",
    group: "Mediocentro",
    positionKeys: POS_MC,
    keyAttributes: ["Desmarques", "Pases", "Visión", "Decisiones", "Control", "Técnica", "Trabajo de equipo", "Sacrificio"],
    preferredAttributes: ["Resistencia", "Serenidad", "Anticipación"],
  },

  // CENTROCAMPISTA POR DENTRO
  {
    id: "centrocampista",
    name: "Centrocampista",
    group: "Centrocampista",
    positionKeys: POS_ME,
    keyAttributes: ["Pases", "Entradas", "Decisiones", "Control", "Trabajo de equipo"],
    preferredAttributes: ["Técnica", "Desmarques", "Colocación"],
  },
  {
    id: "mediapunta-cm",
    name: "Mediapunta (CM)",
    group: "Centrocampista",
    positionKeys: POS_ME,
    keyAttributes: ["Tiros lejanos", "Desmarques", "Pases", "Control", "Técnica", "Talento", "Serenidad"],
    preferredAttributes: ["Regate", "Visión", "Decisiones"],
  },
  {
    id: "organizador-adelantado",
    name: "Organizador adelantado",
    group: "Centrocampista",
    positionKeys: POS_ME,
    keyAttributes: ["Desmarques", "Pases", "Visión", "Decisiones", "Control", "Técnica", "Trabajo de equipo", "Serenidad"],
    preferredAttributes: ["Regate", "Talento", "Anticipación"],
  },
  {
    id: "mediocampista-de-banda",
    name: "Mediocampista de banda",
    group: "Centrocampista",
    positionKeys: POS_ME,
    keyAttributes: ["Pases", "Entradas", "Decisiones", "Control", "Trabajo de equipo"],
    preferredAttributes: ["Centros", "Técnica", "Resistencia"],
  },
  {
    id: "centrocampista-interior",
    name: "Centrocampista interior",
    group: "Centrocampista",
    positionKeys: POS_ME,
    keyAttributes: ["Centros", "Desmarques", "Pases", "Control", "Técnica", "Sacrificio", "Aceleración", "Serenidad"],
    preferredAttributes: ["Regate", "Decisiones", "Trabajo de equipo"],
  },
  {
    id: "centrocampista-organizador",
    name: "Centrocampista organizador",
    group: "Centrocampista",
    positionKeys: POS_ME,
    keyAttributes: ["Desmarques", "Pases", "Visión", "Decisiones", "Control", "Técnica", "Trabajo de equipo", "Serenidad"],
    preferredAttributes: ["Regate", "Talento", "Anticipación"],
  },

  // EXTERIORES (BANDA)
  {
    id: "centrocampista-de-banda",
    name: "Centrocampista de banda",
    group: "Exterior",
    positionKeys: POS_MP_EXT,
    keyAttributes: ["Centros", "Pases", "Decisiones", "Técnica", "Trabajo de equipo", "Sacrificio", "Resistencia", "Velocidad"],
    preferredAttributes: ["Regate", "Desmarques", "Control"],
  },
  {
    id: "extremo",
    name: "Extremo",
    group: "Exterior",
    positionKeys: POS_MP_EXT,
    keyAttributes: ["Centros", "Regate", "Técnica", "Trabajo de equipo", "Aceleración", "Velocidad", "Agilidad"],
    preferredAttributes: ["Desmarques", "Control", "Decisiones"],
  },
  {
    id: "extremo-organizador",
    name: "Extremo organizador",
    group: "Exterior",
    positionKeys: POS_MP_EXT,
    keyAttributes: ["Centros", "Regate", "Desmarques", "Pases", "Visión", "Decisiones", "Control", "Técnica"],
    preferredAttributes: ["Trabajo de equipo", "Serenidad", "Aceleración"],
  },
  {
    id: "extremo-por-dentro",
    name: "Extremo por dentro",
    group: "Exterior",
    positionKeys: POS_MP_EXT,
    keyAttributes: ["Regate", "Control", "Técnica", "Trabajo de equipo", "Aceleración", "Agilidad", "Serenidad"],
    preferredAttributes: ["Desmarques", "Pases", "Decisiones"],
  },
  {
    id: "delantero-por-dentro",
    name: "Delantero por dentro",
    group: "Exterior",
    positionKeys: POS_MP_EXT,
    keyAttributes: ["Regate", "Desmarques", "Anticipación", "Control", "Técnica", "Aceleración", "Agilidad", "Serenidad"],
    preferredAttributes: ["Remate", "Pases", "Decisiones"],
  },
  {
    id: "delantero-escorado",
    name: "Delantero escorado",
    group: "Exterior",
    positionKeys: POS_MP_EXT,
    keyAttributes: ["Regate", "Desmarques", "Anticipación", "Control", "Técnica", "Aceleración", "Velocidad", "Agilidad"],
    preferredAttributes: ["Remate", "Trabajo de equipo", "Concentración"],
  },

  // MEDIAPUNTA POR DENTRO
  {
    id: "rol-libre",
    name: "Rol libre",
    group: "Mediapunta",
    positionKeys: POS_MP_C,
    keyAttributes: ["Regate", "Tiros lejanos", "Desmarques", "Pases", "Visión", "Control", "Técnica", "Talento"],
    preferredAttributes: ["Decisiones", "Serenidad", "Aceleración"],
  },
  {
    id: "mediapunta-mp",
    name: "Mediapunta (MP)",
    group: "Mediapunta",
    positionKeys: POS_MP_C,
    keyAttributes: ["Tiros lejanos", "Desmarques", "Pases", "Control", "Técnica", "Talento", "Serenidad"],
    preferredAttributes: ["Regate", "Visión", "Decisiones"],
  },
  {
    id: "organizador-adelantado-mp",
    name: "Organizador adelantado (MP)",
    group: "Mediapunta",
    positionKeys: POS_MP_C,
    keyAttributes: ["Desmarques", "Pases", "Visión", "Decisiones", "Control", "Técnica", "Trabajo de equipo", "Serenidad"],
    preferredAttributes: ["Regate", "Talento", "Anticipación"],
  },
  {
    id: "segundo-delantero",
    name: "Segundo delantero",
    group: "Mediapunta",
    positionKeys: POS_MP_C,
    keyAttributes: ["Remate", "Desmarques", "Anticipación", "Control", "Aceleración", "Serenidad"],
    preferredAttributes: ["Técnica", "Decisiones", "Trabajo de equipo"],
  },
  {
    id: "centrocampista-interior-mp",
    name: "Centrocampista interior (MP)",
    group: "Mediapunta",
    positionKeys: POS_MP_C,
    keyAttributes: ["Centros", "Desmarques", "Pases", "Control", "Técnica", "Sacrificio", "Aceleración", "Serenidad"],
    preferredAttributes: ["Regate", "Decisiones", "Trabajo de equipo"],
  },

  // DELANTERO CENTRO
  {
    id: "delantero-de-apoyo",
    name: "Delantero de apoyo",
    group: "Delantero",
    positionKeys: POS_DL,
    keyAttributes: ["Remate", "Desmarques", "Control", "Técnica", "Fuerza", "Serenidad"],
    preferredAttributes: ["Cabeceo", "Pases", "Decisiones", "Trabajo de equipo"],
  },
  {
    id: "delantero-centro",
    name: "Delantero centro",
    group: "Delantero",
    positionKeys: POS_DL,
    keyAttributes: ["Remate", "Cabeceo", "Desmarques", "Control", "Técnica", "Aceleración", "Fuerza", "Serenidad"],
    preferredAttributes: ["Decisiones", "Anticipación", "Trabajo de equipo"],
  },
  {
    id: "hombre-objetivo",
    name: "Hombre objetivo",
    group: "Delantero",
    positionKeys: POS_DL,
    keyAttributes: ["Remate", "Cabeceo", "Desmarques", "Fuerza", "Alcance de salto", "Equilibrio", "Valentía", "Agresividad"],
    preferredAttributes: ["Anticipación", "Decisiones", "Trabajo de equipo"],
  },
  {
    id: "ariete",
    name: "Ariete",
    group: "Delantero",
    positionKeys: POS_DL,
    keyAttributes: ["Remate", "Cabeceo", "Desmarques", "Anticipación", "Aceleración", "Serenidad", "Concentración"],
    preferredAttributes: ["Decisiones", "Trabajo de equipo", "Velocidad"],
  },
  {
    id: "delantero-buscaespacios",
    name: "Delantero buscaespacios",
    group: "Delantero",
    positionKeys: POS_DL,
    keyAttributes: ["Remate", "Cabeceo", "Desmarques", "Control", "Técnica", "Aceleración", "Fuerza", "Serenidad"],
    preferredAttributes: ["Decisiones", "Trabajo de equipo", "Anticipación"],
  },
  {
    id: "falso-nueve",
    name: "Falso nueve",
    group: "Delantero",
    positionKeys: POS_DL,
    keyAttributes: ["Regate", "Desmarques", "Pases", "Visión", "Decisiones", "Control", "Técnica", "Trabajo de equipo"],
    preferredAttributes: ["Resistencia", "Serenidad", "Anticipación"],
  },
];
